### ISSUE TITLE
[EnphaseEnvoy] Add ability to configure username

### ISSUE THREAD

**Issue by gtdiehl** [HentschelT/openhab2-addons#14]
## Expected Behavior

In PaperUI add another configuration parameter to configure username

## Current Behavior

Currently unable to change the username of 'envoy' that is in the code.  Which means the binding does not collect inverter data from the Envoy-R.

## Steps to Reproduce (for Bugs)

1. Install emphase binding
2. Connect to Envoy-R running v3.x firmware

## Context

My Envoy requires a username of 'installer' to be able to access the Inverter production page

**Comment by lsiepel** [comment]
@gtdiehl I think this is fixed with a new binding from a different dev:
https://github.com/Hilbrand/openhab-addons/tree/enphase/bundles/org.openhab.binding.enphase
Discussion here: https://community.openhab.org/t/new-binding-enphase-envoy-solar-system-gateway/44449
